openapi: 3.0.0
info:
  title: Payment Status API
  version: 1.0.0
  description: API for managing payment blocking status for clients.
servers:
  - url: https://api.yourdomain.com/v1
    description: Production server

paths:
  /clients/{clientId}/block:
    post:
      summary: Block a client's payments
      operationId: blockClientPayments
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: Unique identifier of the client
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                  enum: [fraud, incorrect_details]
                  description: Reason for blocking the client's payments
      responses:
        '200':
          description: Payment status updated to blocked
        '404':
          description: Client not found
        '400':
          description: Invalid input

  /clients/{clientId}/unblock:
    post:
      summary: Unblock a client's payments
      operationId: unblockClientPayments
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: Unique identifier of the client
          schema:
            type: integer
      responses:
        '200':
          description: Payment status updated to unblocked
        '404':
          description: Client not found
        '400':
          description: Invalid input

  /clients/{clientId}/status:
    get:
      summary: Check if a client's payments are blocked and for what reason
      operationId: checkClientPaymentStatus
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: Unique identifier of the client
          schema:
            type: integer
      responses:
        '200':
          description: Payment status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientId:
                    type: integer
                  status:
                    type: string
                    enum: [block, unblock]
                  reason:
                    type: string
                    enum: [fraud, incorrect_details, not blocked]
        '404':
          description: Client not found

  /clients/{clientId}/block-history:
      get:
        summary: Retrieve the block history of a client
        operationId: getClientBlockHistory
        tags:
          - clients
        parameters:
          - name: clientId
            in: path
            required: true
            description: Unique identifier of the client
            schema:
              type: integer
        responses:
          '200':
            description: Block history retrieved successfully
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      historyId:
                        type: integer
                        description: Unique identifier of the block history record
                      status:
                        type: string
                        enum: [block, unblock]
                        description: Status of the block
                      reason:
                        type: string
                        enum: [fraud, incorrect_details, other]
                        description: Reason for the block
                      dateFrom:
                        type: string
                        format: date-time
                        description: Timestamp when the block was initiated
                      dateTo:
                        type: string
                        format: date-time
                        description: Timestamp when the block was lifted, if applicable
          '404':
            description: Client not found
            